export const projects_resource = [
  {
    title: 'Casa GB',
    hoverText: 'Casa GB',
    coverImage: './assets/images/projects/CasaGB/1.jpg',
    id: 1,
  },
  {
    title: 'Casa GB 2',
    hoverText: 'Casa GB 2',
    coverImage: './assets/images/projects/CasaGB/2.jpg',
    id: 2,
  },
  {
    title: 'Titulo 3',
    hoverText: 'Hover Text 3',
    coverImage: './assets/images/projects/background.jpg',
    id: 3,
  },
  {
    title: 'Titulo 4',
    hoverText: 'Hover Text 4',
    coverImage: './assets/images/projects/background.jpg',
    id: 4,
  },
  {
    title: 'Titulo 5',
    hoverText: 'Hover Text 5',
    coverImage: './assets/images/projects/background.jpg',
    id: 5,
  },
  {
    title: 'Titulo 6',
    hoverText: 'Hover Text 6',
    coverImage: './assets/images/projects/background.jpg',
    id: 6,
  },
  {
    title: 'Titulo 7',
    hoverText: 'Hover Text 7',
    coverImage: './assets/images/projects/background.jpg',
    id: 7,
  },
  {
    title: 'Titulo 8',
    hoverText: 'Hover Text 8',
    coverImage: './assets/images/projects/background.jpg',
    id: 8,
  },
  {
    title: 'Titulo 9',
    hoverText: 'Hover Text 9',
    coverImage: './assets/images/projects/background.jpg',
    id: 9,
  },
  {
    title: 'Titulo 10',
    hoverText: 'Hover Text 10',
    coverImage: './assets/images/projects/background.jpg',
    id: 10,
  },
  {
    title: 'Titulo 11',
    hoverText: 'Hover Text 11',
    coverImage: './assets/images/projects/background.jpg',
    id: 11,
  },
  {
    title: 'Titulo 12',
    hoverText: 'Hover Text 12',
    coverImage: './assets/images/projects/background.jpg',
    id: 12,
  },
  {
    title: 'Titulo 13',
    hoverText: 'Hover Text 13',
    coverImage: './assets/images/projects/background.jpg',
    id: 13,
  },
  {
    title: 'Titulo 14',
    hoverText: 'Hover Text 14',
    coverImage: './assets/images/projects/background.jpg',
    id: 14,
  },
  {
    title: 'Titulo 15',
    hoverText: 'Hover Text 15',
    coverImage: './assets/images/projects/background.jpg',
    id: 15,
  },
  {
    title: 'Titulo 16',
    hoverText: 'Hover Text 16',
    coverImage: './assets/images/projects/background.jpg',
    id: 16,
  },
  {
    title: 'Titulo 17',
    hoverText: 'Hover Text 17',
    coverImage: './assets/images/projects/background.jpg',
    id: 17,
  },
  {
    title: 'Titulo 18',
    hoverText: 'Hover Text 18',
    coverImage: './assets/images/projects/background.jpg',
    id: 18,
  },
  {
    title: 'Titulo 19',
    hoverText: 'Hover Text 19',
    coverImage: './assets/images/projects/background.jpg',
    id: 19,
  },
  {
    title: 'Titulo 20',
    hoverText: 'Hover Text 20',
    coverImage: './assets/images/projects/background.jpg',
    id: 20,
  },
];
